FROM golang:1.23-alpine
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY icmp-probe-service.go ./
RUN go build -o /usr/local/bin/probe-service icmp-probe-service.go
EXPOSE 9900
CMD ["/usr/local/bin/probe-service"]
